### PR TITLE
Added spanish translation and jitpack.io support for this library. Released version 0.2.1.

### PR DESCRIPTION
**Pull request by GrenderG**

### CODE REVIEW

**Comment by GrenderG** [comment]
Please do a release with tag version 0.2.1 in order to use it with JitPack.

**Comment by nwalters512** [comment]
Thanks for the contributions!

In the future, if you could split unrelated changes into separate pull requests, that would be great.

Is there any particular reason I should start hosting on jitpack? It looks to do the same thing as jCenter and Maven.

**Comment by nwalters512** [comment]
Also, please don't bump the version code in PRs, I'll do that once I'm ready to do a release.

**Comment by GrenderG** [comment]
Yeah, sorry for that. I like using JitPack because is very simple and is always updated when you release a new version.

**Comment by nwalters512** [comment]
I gotcha. That being said, I'm going to stick with the current release system. jCenter and Maven are standard for Android libraries, and they let us keep a consistent group ID.

If you'd like to get credit for your translations, you can open a new PR with just that commit, or I can add them to the project myself.

**Pull request closed without merging**
