### PR TITLE
Grey circle for disabled SpectrumPreference

### PR DESCRIPTION
**Pull request by francoiscampbell**
Show a grey circle (actually black @ 38% alpha) for a disabled preference

### CODE REVIEW

**Comment by nwalters512** [comment]
Good call with using alpha instead of hardcoded gray! Can you add a demo of this feature to the preference tab as well?

**Comment by francoiscampbell** [comment]
Done

**Comment by nwalters512** [comment]
Looking good! One final thought I had that I'd like your opinion on: what about just showing an outline instead of the full circle? That, combined with the gray, should indicate pretty well that it's disabled. Compare the existing and proposed implementations below:

Existing:
Imgur

Proposed:
Imgur

**Comment by francoiscampbell** [comment]
Yeah, I like that way better, it really conveys that it's disabled. I did think the full grey circle was a bit too prominent due to its size but I left it as-as because it's Material spec.

EDIT: on an unrelated note, is it just me or are the two top circles smaller than the bottom two?

**Comment by nwalters512** [comment]
They definitely are; they're set to use a border in the prefs xml file. It just so happens that the border is applied regardless of whether or not the color actually needs a border. In this case, the white border shrinks the amount of the real color that's visible.

I'm going to merge this PR, then make it just the ring and clean up the border behavior in one go.

**Pull request merged**
